### ISSUE TITLE
Feature Request: Log Manintenance

### ISSUE THREAD

**Issue by Gorsis** [guildantix/eq-parse#1]
Can we have an archive storage location selection option, for Log Maintenance.

With Gina, I have had Achived logs store on a storage drive, instead of in the EQ folder.

**Comment by guildantix** [comment]
Sorry, I do most of this through my discord. Just noticed there were some feature requests in here.  This has been added, but I'll add something in my list to allow the user to select a directory.

**Comment by guildantix** [comment]
Actually, I added this to my feature requests discord just to keep it all in the same area, closing the thread here.
https://discord.gg/p8hu3w2WkE
