### ISSUE TITLE
Cannot import new audio files

### ISSUE THREAD

**Issue by p-clem** [guildantix/eq-parse#19]
![image](https://github.com/guildantix/eq-nag/assets/7556471/0eb2b59a-a987-4a20-818f-88b1b558dcd0)

It's not possible to add new audio files. Whenever I select a new file it's not uploaded to the sound library and therefore I cannot select any sound beside the 4 default ones

**Comment by Praxeomatic** [comment]
How did you resolve this problem, p-clem?  The "Select New Audio Clip" button appears to do nothing, and there does not seem to be a particular location that NAG is looking for a list of audio clips.
![image](https://github.com/user-attachments/assets/a7a2a092-d8d4-4696-b0bb-9027e8796b0f)
