### ISSUE TITLE
Feature Request: Trigger fired list

### ISSUE THREAD

**Issue by KestrelKitezh** [guildantix/eq-parse#2]
In gina you have a list which adds each time a trigger fires. Also possible to just click the line to open up that specific trigger. I love this feature, and would love to see some kind of option for this in NAG

**Comment by guildantix** [comment]
Hey, I'm working on that this weekend!  Gonna add this to my feature request channel so they're all in the same place.
I don't check github issues often, most reports and feature requests go through my discord server: https://discord.gg/p8hu3w2WkE
