### ISSUE TITLE
Feature request: Vertical Scroll bar for triggers

### ISSUE THREAD

**Issue by Albin-Gedda** [guildantix/eq-parse#4]
A Vertical scroll bar for triggers.
As it is now, importing my Raid folder from Gina with all triggers for every raid in game shows an insane list of triggers (1700+) that would be easier to navigate with a scroll bar

**Comment by guildantix** [comment]
That's a ton of triggers.  Also, you may want to share them at some point, so shoot me a DM on discord or something to let me know and I can help you get added to the public library.
Either way, I'll add it to my feature requests channel just to keep them all in the same place.
I don't check github issues often, most reports and feature requests go through my discord server: https://discord.gg/p8hu3w2WkE
