### ISSUE TITLE
Feature request: Activate/Inactivate folder by single press

### ISSUE THREAD

**Issue by Albin-Gedda** [guildantix/eq-parse#5]
Instead of having to select active/inactive per trigger I would like to be able to activate/inactivate a folder

**Comment by guildantix** [comment]
This is actually already on my list, someone else had requested something very similar somewhere else.  I'll add it to my feature requests channel just to keep them all in the same place.
I don't check github issues often, most reports and feature requests go through my discord server: https://discord.gg/p8hu3w2WkE
