### ISSUE TITLE
Feature request: Show only trigger in selected folder

### ISSUE THREAD

**Issue by Albin-Gedda** [guildantix/eq-parse#6]
As it is now, if I have a trigger folder with subfolder. Everything in every subfolder will be shown, or when clicking the folder. it toggles view to show every single trigger. How about a 3rd option in that cycle, only show trigger in the specific folder?

**Comment by guildantix** [comment]
I'll add it to my feature requests channel just to keep them all in the same place.
I don't check github issues often, most reports and feature requests go through my discord server: https://discord.gg/p8hu3w2WkE
