### ISSUE TITLE
Feature request: Simulate log as {Class} {Level}

### ISSUE THREAD

**Issue by Albin-Gedda** [guildantix/eq-parse#8]
When simulating logs it would help to be able to also simulate what Class and Level I am, to verify my triggers work as intended.
Maybe checkbox for class (to verify multiple at once) and textbox for level

**Comment by guildantix** [comment]
This has actually been on my list for a bit now, I'll add it to my feature requests channel just to keep them all in the same place.
I don't check github issues often, most reports and feature requests go through my discord server: https://discord.gg/p8hu3w2WkE
